# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glvmlss_rcpp <- function(Yr, famr, q, b, control) {
    .Call(`_glvmlss_glvmlss_rcpp`, Yr, famr, q, b, control)
}

glvmlss_rcpp_sim <- function(n, famr, q, b, control) {
    .Call(`_glvmlss_glvmlss_rcpp_sim`, n, famr, q, b, control)
}

